language: python
python:
  - 3.8

services:
  - docker

install:
  - pip install codecov

before_script:
  - pip install docker-compose

script:
  - docker-compose up -d
  - docker exec -it $(docker ps -aqf "name=todo-list_web") /bin/sh -c "pytest --ignore=frontend --ignore=e2e --cov-report=xml --cov-config=.coveragerc --cov=. -n auto"
  - docker cp $(docker ps -aqf "name=todo-list_web"):/usr/src/app/coverage.xml .
  - docker exec -it $(docker ps -aqf "name=todo-list_web") /bin/sh -c "mypy ."
  - docker exec -it $(docker ps -aqf "name=todo-list_web") /bin/sh -c "flake8"
  - docker exec -it $(docker ps -aqf "name=todo-list_web") /bin/sh -c "cd frontend && npm run test"
  - docker cp $(docker ps -aqf "name=todo-list_web"):/usr/src/frontend/coverage .
  - docker exec -it $(docker ps -aqf "name=todo-list_web") /bin/sh -c "cd frontend && npm run eslint"

after_success:
  - bash <(curl -s https://codecov.io/bash) -cF python
  - bash <(curl -s https://codecov.io/bash) -cF javascript
